title: Gitpod Config
tasks:
  - prebuild: npm i -g pnpm
  - command: pnpm install
  - command: pnpm dev --open --host --port 3000
vscode:
extensions:
- octref.vetur
- tabnine.tabnine-vscode
- esbenp.prettier-vscode
- dbaeumer.vscode-eslint
- antfu.vite
- antfu.iconify
- antfu.slidev
- editorconfig.editorconfig
- antfu.theme-vitesse
