// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogRepo: typeof import('./src/components/BlogRepo.vue')['default']
    CBD: typeof import('./src/components/CBD.md')['default']
    ContentLayout: typeof import('./src/components/ContentLayout.vue')['default']
    DynamicRoute: typeof import('./src/components/DynamicRoute.vue')['default']
    MyButton: typeof import('./src/components/MyButton.vue')['default']
    MyContent: typeof import('./src/components/MyContent.vue')['default']
    MyFaq: typeof import('./src/components/MyFaq.vue')['default']
    MyBanner: typeof import('./src/components/myBanner.vue')['default']
    MyFeature: typeof import('./src/components/myFeature.vue')['default']
    MyHeader: typeof import('./src/components/myHeader.vue')['default']
    MyHero: typeof import('./src/components/myHero.vue')['default']
    MyPricing: typeof import('./src/components/myPricing.vue')['default']
    MyTeam: typeof import('./src/components/myTeam.vue')['default']
    MyUpdates: typeof import('./src/components/myUpdates.vue')['default']
  }
}

export { }
